server:
  port: 8021
spring:
  application:
    name: rabbitmq-learning
  rabbitmq:
    listener:
      simple:
        prefetch: 1
    host: 127.0.0.1
    port: 5674
    username: admin
    password: 8888.216
    virtualHost: my_vhost
